<?php

return [
    'permissions' => [
        'Site',
        'ContactPerson',
        'Server',
        'VM',
        'NAS',
        'SecurepointUTM',
        'Router',
        'Network',
        'NetworkSwitch',
        'Wifi',
        'Accesspoint',
        'Computer',
        'IoTDevice',
        'Machine',
        'OtherClient',
        'Printer',
        'ADDomain',
        'ADUser',
        'ADGroup',
        'PhoneSystem',
        'Phone',
        'DECT',
        'LoginGeneral',
        'LoginNAS',
        'LoginWebsite',
        'LoginRecorder',
        'SecurepointUMA',
        'Mailbox',
        'Recorder',
        'Camera',
        'LicenseSoftware',
        'LicenseWindows',
        'LicenseAccess',
        'FTPServer',
        'DynDNS',
        'File',
        'Ups',
        'InternetConnection',
        'Domain',
        'Certificate',
        'Backup'
    ],

    /*
     * Whitelist für den Papierkorb: URL-Slug => [Model-Klasse, Anzeigename].
     * Nur Models mit customer_id und SoftDeletes aufnehmen.
     */
    'trashables' => [
        'site' => [\App\Models\Site::class, 'Standort'],
        'contactperson' => [\App\Models\ContactPerson::class, 'Ansprechpartner'],
        'server' => [\App\Models\Server::class, 'Server'],
        'vm' => [\App\Models\VM::class, 'VM'],
        'nas' => [\App\Models\NAS::class, 'NAS'],
        'securepointutm' => [\App\Models\SecurepointUTM::class, 'Securepoint UTM'],
        'securepointuma' => [\App\Models\SecurepointUMA::class, 'E-Mail-Archivierung'],
        'router' => [\App\Models\Router::class, 'Router'],
        'network' => [\App\Models\Network::class, 'Netzwerk'],
        'networkswitch' => [\App\Models\NetworkSwitch::class, 'Switch'],
        'wifi' => [\App\Models\Wifi::class, 'WLAN'],
        'accesspoint' => [\App\Models\Accesspoint::class, 'Accesspoint'],
        'computer' => [\App\Models\Computer::class, 'Computer'],
        'iotdevice' => [\App\Models\IoTDevice::class, 'IoT-Gerät'],
        'machine' => [\App\Models\Machine::class, 'Maschine'],
        'otherclient' => [\App\Models\OtherClient::class, 'Sonstiger Client'],
        'printer' => [\App\Models\Printer::class, 'Drucker'],
        'addomain' => [\App\Models\ADDomain::class, 'AD-Domäne'],
        'aduser' => [\App\Models\ADUser::class, 'AD-Benutzer'],
        'adgroup' => [\App\Models\ADGroup::class, 'AD-Gruppe'],
        'phonesystem' => [\App\Models\PhoneSystem::class, 'TK-Anlage'],
        'phone' => [\App\Models\Phone::class, 'Telefon'],
        'dect' => [\App\Models\DECT::class, 'DECT'],
        'logingeneral' => [\App\Models\LoginGeneral::class, 'Login Allgemein'],
        'loginnas' => [\App\Models\LoginNAS::class, 'Login NAS'],
        'loginwebsite' => [\App\Models\LoginWebsite::class, 'Login Webseite'],
        'loginrecorder' => [\App\Models\LoginRecorder::class, 'Login Recorder'],
        'mailbox' => [\App\Models\Mailbox::class, 'Postfach'],
        'recorder' => [\App\Models\Recorder::class, 'Recorder'],
        'camera' => [\App\Models\Camera::class, 'Kamera'],
        'licensesoftware' => [\App\Models\LicenseSoftware::class, 'Software-Lizenz'],
        'licensewindows' => [\App\Models\LicenseWindows::class, 'Windows-Lizenz'],
        'licenseaccess' => [\App\Models\LicenseAccess::class, 'CAL-Lizenz'],
        'ftpserver' => [\App\Models\FTPServer::class, 'FTP-Server'],
        'dyndns' => [\App\Models\DynDNS::class, 'DynDNS'],
        'ups' => [\App\Models\Ups::class, 'USV'],
        'internetconnection' => [\App\Models\InternetConnection::class, 'Internet-Anschluss'],
        'domain' => [\App\Models\Domain::class, 'Domain'],
        'certificate' => [\App\Models\Certificate::class, 'Zertifikat'],
        'backup' => [\App\Models\Backup::class, 'Backup'],
    ],

    /**
     * Überschrift der Listen-Seiten. Die trashables-Labels oben benennen ein
     * einzelnes Objekt ("Zertifikat wiederhergestellt") und passen deshalb nicht
     * als Titel einer Liste. Hier steht die Mehrzahl, und zwar in der Schreibweise
     * aus der Seitenleiste — der Nutzer klickt dort und erwartet oben dasselbe Wort.
     * Fehlt ein Schlüssel, greift automatisch das trashables-Label.
     */
    'list_titles' => [
        'site' => 'Standorte',
        'vm' => 'VMs',
        'network' => 'VLANs',
        'wifi' => 'WLAN-Netze',
        'machine' => 'Maschinen',
        'otherclient' => 'Sonstige Clients',
        'printer' => 'Drucker',
        'addomain' => 'AD-Domänen',
        'aduser' => 'AD-Benutzer',
        'adgroup' => 'AD-Gruppen',
        'phonesystem' => 'TK-Anlagen',
        'phone' => 'Telefone',
        'logingeneral' => 'Logins Allgemein',
        'loginnas' => 'Logins NAS',
        'loginwebsite' => 'Logins Webseiten',
        'loginrecorder' => 'Logins Recorder',
        'mailbox' => 'E-Mail-Postfächer',
        'recorder' => 'Recorder',
        'camera' => 'Kameras',
        'licensesoftware' => 'Software-Lizenzen',
        'licensewindows' => 'Windows-Lizenzen',
        'licenseaccess' => 'CAL-Lizenzen',
        'ftpserver' => 'FTP-Server',
        'internetconnection' => 'Internet-Anschlüsse',
        'domain' => 'Domains',
        'certificate' => 'Zertifikate',
        'backup' => 'Backups',
        'iotdevice' => 'IoT-Geräte',
        'networkswitch' => 'Switches',
        'accesspoint' => 'Accesspoints',
        'contactperson' => 'Ansprechpartner',
    ],
];
